name: 'CI/CD'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo (shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up GAMS
        run: ./scripts/setup-gams.sh
      - name: Run unit tests
        run: ./gradlew build
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Clone repo (shallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: develop
          # only extracting the server address to a secret avoids leaking it in the logs
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_SERVER_ADDRESS }}/toolbox-backend-staging
          ssh_private_key: ${{ secrets.DOKKU_DEPLOYMENT_KEY }}
